# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
# Forge for 1.19.3 is version 44
loaderVersion="[43,)"
# The license for your mod. This is mandatory and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All Rights Reserved"
# A URL to refer people to when problems occur with this mod
# issueTrackerURL="github.com/MinecraftForge/MinecraftForge/issues"
# If the mods defined in this file should show as separate resource packs
showAsResourcePack=false

[[mods]]
  modId="creeperhive"
  version="1.0.0.0"
  displayName="Creeper Hive"
  # updateJSONURL="minecraftforge.net/versions.json"
  displayURL="minecraftforge.net"
  logoFile="logo.png"
  credits="UXD on DeviantArt for original concept."
  authors="OceanusProcellarum"
  description='''
  Creepers, but with an invertebrate lifecycle
  '''
  displayTest="MATCH_VERSION"


#  [[dependencies.creeperhive]]
#    modId="forge"
#    mandatory=true
#    versionRange="[43,)"
#    ordering="NONE"
#    side="BOTH"

#  [[dependencies.creeperhive]]
#    modId="minecraft"
#    mandatory=true
#    versionRange="[1.19.2,1.20)"
#    ordering="NONE"
#    side="BOTH"
